-- ============================================================================
-- Cine Zaror — 03_constraints.sql
-- Claves primarias, foráneas, únicas, CHECK e índices recomendados.
-- Fuentes: docs/03-modelo-datos.md, docs/04-objetos-oracle.md
-- ============================================================================

-- ============================================================================
-- CLAVES PRIMARIAS
-- ============================================================================

ALTER TABLE ROL
    ADD CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL);

ALTER TABLE USUARIO
    ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO);

ALTER TABLE PELICULA
    ADD CONSTRAINT PK_PELICULA PRIMARY KEY (ID_PELICULA);

ALTER TABLE SALA
    ADD CONSTRAINT PK_SALA PRIMARY KEY (ID_SALA);

ALTER TABLE ASIENTO
    ADD CONSTRAINT PK_ASIENTO PRIMARY KEY (ID_ASIENTO);

ALTER TABLE FUNCION
    ADD CONSTRAINT PK_FUNCION PRIMARY KEY (ID_FUNCION);

ALTER TABLE ESTADO_RESERVA
    ADD CONSTRAINT PK_ESTADO_RESERVA PRIMARY KEY (ID_ESTADO);

ALTER TABLE RESERVA
    ADD CONSTRAINT PK_RESERVA PRIMARY KEY (ID_RESERVA);

ALTER TABLE RESERVA_ASIENTO
    ADD CONSTRAINT PK_RESERVA_ASIENTO PRIMARY KEY (ID_RESERVA_ASIENTO);

ALTER TABLE PAGO
    ADD CONSTRAINT PK_PAGO PRIMARY KEY (ID_PAGO);

ALTER TABLE AUDITORIA_RESERVA
    ADD CONSTRAINT PK_AUDITORIA_RESERVA PRIMARY KEY (ID_AUDITORIA);

-- ============================================================================
-- CLAVES FORÁNEAS
-- Relaciones documentadas en docs/03-modelo-datos.md (sección 2)
-- ============================================================================

ALTER TABLE USUARIO
    ADD CONSTRAINT FK_USUARIO_ROL
    FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL);

ALTER TABLE ASIENTO
    ADD CONSTRAINT FK_ASIENTO_SALA
    FOREIGN KEY (ID_SALA) REFERENCES SALA (ID_SALA);

ALTER TABLE FUNCION
    ADD CONSTRAINT FK_FUNCION_PELICULA
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA (ID_PELICULA);

ALTER TABLE FUNCION
    ADD CONSTRAINT FK_FUNCION_SALA
    FOREIGN KEY (ID_SALA) REFERENCES SALA (ID_SALA);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_FUNCION
    FOREIGN KEY (ID_FUNCION) REFERENCES FUNCION (ID_FUNCION);

ALTER TABLE RESERVA
    ADD CONSTRAINT FK_RESERVA_ESTADO
    FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO_RESERVA (ID_ESTADO);

ALTER TABLE RESERVA_ASIENTO
    ADD CONSTRAINT FK_RESERVA_ASIENTO_RESERVA
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA (ID_RESERVA);

ALTER TABLE RESERVA_ASIENTO
    ADD CONSTRAINT FK_RESERVA_ASIENTO_FUNCION
    FOREIGN KEY (ID_FUNCION) REFERENCES FUNCION (ID_FUNCION);

ALTER TABLE RESERVA_ASIENTO
    ADD CONSTRAINT FK_RESERVA_ASIENTO_ASIENTO
    FOREIGN KEY (ID_ASIENTO) REFERENCES ASIENTO (ID_ASIENTO);

ALTER TABLE PAGO
    ADD CONSTRAINT FK_PAGO_RESERVA
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA (ID_RESERVA);

ALTER TABLE AUDITORIA_RESERVA
    ADD CONSTRAINT FK_AUDITORIA_RESERVA
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA (ID_RESERVA);

-- ============================================================================
-- RESTRICCIONES UNIQUE
-- ============================================================================

ALTER TABLE ROL
    ADD CONSTRAINT UQ_ROL_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE USUARIO
    ADD CONSTRAINT UQ_USUARIO_RUT UNIQUE (RUT);

ALTER TABLE USUARIO
    ADD CONSTRAINT UQ_USUARIO_CORREO UNIQUE (CORREO);

ALTER TABLE SALA
    ADD CONSTRAINT UQ_SALA_NOMBRE UNIQUE (NOMBRE);

-- RN-12: no puede haber dos asientos con igual fila y número en la misma sala
ALTER TABLE ASIENTO
    ADD CONSTRAINT UQ_ASIENTO_SALA_FILA_NUMERO UNIQUE (ID_SALA, FILA, NUMERO);

ALTER TABLE ESTADO_RESERVA
    ADD CONSTRAINT UQ_ESTADO_RESERVA_NOMBRE UNIQUE (NOMBRE);

ALTER TABLE RESERVA
    ADD CONSTRAINT UQ_RESERVA_CODIGO UNIQUE (CODIGO);

-- Protección principal contra venta doble de asiento en una función
ALTER TABLE RESERVA_ASIENTO
    ADD CONSTRAINT UQ_RESERVA_ASIENTO_FUNCION_ASIENTO UNIQUE (ID_FUNCION, ID_ASIENTO);

-- Relación 1:1 RESERVA — PAGO (docs/03-modelo-datos.md sección 2)
ALTER TABLE PAGO
    ADD CONSTRAINT UQ_PAGO_RESERVA UNIQUE (ID_RESERVA);

ALTER TABLE PAGO
    ADD CONSTRAINT UQ_PAGO_CODIGO_OPERACION UNIQUE (CODIGO_OPERACION);

-- ============================================================================
-- RESTRICCIONES CHECK
-- ============================================================================

-- Película: duración positiva
ALTER TABLE PELICULA
    ADD CONSTRAINT CK_PELICULA_DURACION_POSITIVA
    CHECK (DURACION_MINUTOS > 0);

-- Sala: dimensiones positivas
ALTER TABLE SALA
    ADD CONSTRAINT CK_SALA_FILAS_POSITIVAS
    CHECK (FILAS > 0);

ALTER TABLE SALA
    ADD CONSTRAINT CK_SALA_COLUMNAS_POSITIVAS
    CHECK (COLUMNAS > 0);

-- Función: precio positivo
ALTER TABLE FUNCION
    ADD CONSTRAINT CK_FUNCION_PRECIO_POSITIVO
    CHECK (PRECIO > 0);

-- Reserva: cantidad y total válidos
ALTER TABLE RESERVA
    ADD CONSTRAINT CK_RESERVA_CANTIDAD_POSITIVA
    CHECK (CANTIDAD_ENTRADAS > 0);

ALTER TABLE RESERVA
    ADD CONSTRAINT CK_RESERVA_TOTAL_NO_NEGATIVO
    CHECK (TOTAL >= 0);

-- Flags de estado activo/inactivo (valores binarios documentados como NUMBER(1))
ALTER TABLE USUARIO
    ADD CONSTRAINT CK_USUARIO_ACTIVO
    CHECK (ACTIVO IN (0, 1));

ALTER TABLE PELICULA
    ADD CONSTRAINT CK_PELICULA_ACTIVA
    CHECK (ACTIVA IN (0, 1));

ALTER TABLE SALA
    ADD CONSTRAINT CK_SALA_ACTIVA
    CHECK (ACTIVA IN (0, 1));

ALTER TABLE ASIENTO
    ADD CONSTRAINT CK_ASIENTO_ACTIVO
    CHECK (ACTIVO IN (0, 1));

ALTER TABLE FUNCION
    ADD CONSTRAINT CK_FUNCION_ACTIVA
    CHECK (ACTIVA IN (0, 1));

-- ============================================================================
-- ÍNDICES RECOMENDADOS
-- Fuente: docs/03-modelo-datos.md (sección 3)
-- ============================================================================

CREATE INDEX IDX_FUNCION_FECHA
    ON FUNCION (FECHA_HORA);

CREATE INDEX IDX_FUNCION_PELICULA
    ON FUNCION (ID_PELICULA);

CREATE INDEX IDX_FUNCION_SALA
    ON FUNCION (ID_SALA);

CREATE INDEX IDX_RESERVA_USUARIO
    ON RESERVA (ID_USUARIO);

CREATE INDEX IDX_RESERVA_FUNCION
    ON RESERVA (ID_FUNCION);

CREATE INDEX IDX_RESERVA_ASIENTO_FUNCION
    ON RESERVA_ASIENTO (ID_FUNCION);

CREATE INDEX IDX_ASIENTO_SALA
    ON ASIENTO (ID_SALA);
