-- Datos iniciales de demostración

-- Roles del sistema
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (SEQ_ROL.NEXTVAL, 'ADMIN', 'Administrador del sistema');
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (SEQ_ROL.NEXTVAL, 'CLIENTE', 'Cliente del cine');


-- Estados de reserva
INSERT INTO ESTADO_RESERVA (ID_ESTADO, NOMBRE) VALUES (SEQ_ESTADO_RESERVA.NEXTVAL, 'PENDIENTE');
INSERT INTO ESTADO_RESERVA (ID_ESTADO, NOMBRE) VALUES (SEQ_ESTADO_RESERVA.NEXTVAL, 'PAGADA');
INSERT INTO ESTADO_RESERVA (ID_ESTADO, NOMBRE) VALUES (SEQ_ESTADO_RESERVA.NEXTVAL, 'ANULADA');
INSERT INTO ESTADO_RESERVA (ID_ESTADO, NOMBRE) VALUES (SEQ_ESTADO_RESERVA.NEXTVAL, 'VENCIDA');


-- Usuarios demo (password: Secreta123)
DECLARE
    V_ID_ROL_ADMIN   NUMBER;
    V_ID_ROL_CLIENTE NUMBER;
    V_HASH           VARCHAR2(255) := '$2b$12$kNFBzLqMHVfFZe0rDL9ycexc6kehoLkdGxPfe6.vCQH04Q1eA.iO6';
BEGIN
    SELECT ID_ROL INTO V_ID_ROL_ADMIN FROM ROL WHERE NOMBRE = 'ADMIN';
    SELECT ID_ROL INTO V_ID_ROL_CLIENTE FROM ROL WHERE NOMBRE = 'CLIENTE';

    INSERT INTO USUARIO (ID_USUARIO, ID_ROL, RUT, NOMBRE_COMPLETO, CORREO, PASSWORD_HASH, ACTIVO)
    VALUES (SEQ_USUARIO.NEXTVAL, V_ID_ROL_ADMIN, '99.999.999-9', 'Admin Zaror', 'admin@cinezaror.cl', V_HASH, 1);

    INSERT INTO USUARIO (ID_USUARIO, ID_ROL, RUT, NOMBRE_COMPLETO, CORREO, PASSWORD_HASH, ACTIVO)
    VALUES (SEQ_USUARIO.NEXTVAL, V_ID_ROL_CLIENTE, '12.345.678-9', 'Juan Pérez', 'juan@email.com', V_HASH, 1);

    INSERT INTO USUARIO (ID_USUARIO, ID_ROL, RUT, NOMBRE_COMPLETO, CORREO, PASSWORD_HASH, ACTIVO)
    VALUES (SEQ_USUARIO.NEXTVAL, V_ID_ROL_CLIENTE, '18.765.432-1', 'María López', 'maria@email.com', V_HASH, 1);
END;
/


-- Películas de ejemplo
DECLARE
    V_ID NUMBER;
BEGIN
    SP_CREAR_PELICULA('Intensamente 2', 'Riley enfrenta nuevas emociones.', 96, 'TE', 'Animación', NULL, V_ID);
    SP_CREAR_PELICULA('Deadpool y Wolverine', 'Unión improbable de antihéroes.', 128, 'R', 'Acción', NULL, V_ID);
    SP_CREAR_PELICULA('El Señor de los Anillos', 'La comunidad del anillo.', 178, 'TE', 'Fantasía', NULL, V_ID);
END;
/


-- Salas con asientos generados
DECLARE
    V_ID_SALA1 NUMBER;
    V_ID_SALA2 NUMBER;
BEGIN
    SP_CREAR_SALA('Sala 1', 5, 10, V_ID_SALA1);
    SP_GENERAR_ASIENTOS_SALA(V_ID_SALA1);

    SP_CREAR_SALA('Sala 2', 4, 8, V_ID_SALA2);
    SP_GENERAR_ASIENTOS_SALA(V_ID_SALA2);
END;
/


-- Funciones programadas
DECLARE
    V_P1 NUMBER; V_P2 NUMBER; V_P3 NUMBER;
    V_S1 NUMBER; V_S2 NUMBER;
    V_F  NUMBER;
BEGIN
    SELECT ID_PELICULA INTO V_P1 FROM PELICULA WHERE TITULO = 'Intensamente 2';
    SELECT ID_PELICULA INTO V_P2 FROM PELICULA WHERE TITULO = 'Deadpool y Wolverine';
    SELECT ID_PELICULA INTO V_P3 FROM PELICULA WHERE TITULO = 'El Señor de los Anillos';
    SELECT ID_SALA INTO V_S1 FROM SALA WHERE NOMBRE = 'Sala 1';
    SELECT ID_SALA INTO V_S2 FROM SALA WHERE NOMBRE = 'Sala 2';

    SP_CREAR_FUNCION(V_P1, V_S1, SYSTIMESTAMP + INTERVAL '1' DAY + INTERVAL '18' HOUR, 6000, V_F);
    SP_CREAR_FUNCION(V_P1, V_S1, SYSTIMESTAMP + INTERVAL '1' DAY + INTERVAL '21' HOUR, 6000, V_F);
    SP_CREAR_FUNCION(V_P2, V_S2, SYSTIMESTAMP + INTERVAL '2' DAY + INTERVAL '20' HOUR, 8000, V_F);
    SP_CREAR_FUNCION(V_P3, V_S1, SYSTIMESTAMP + INTERVAL '3' DAY + INTERVAL '19' HOUR, 7500, V_F);
    SP_CREAR_FUNCION(V_P3, V_S2, SYSTIMESTAMP + INTERVAL '3' DAY + INTERVAL '22' HOUR, 7500, V_F);
END;
/


-- Reserva pagada de ejemplo
DECLARE
    V_ID_USUARIO  NUMBER;
    V_ID_FUNCION  NUMBER;
    V_ID_ASIENTO1 NUMBER;
    V_ID_ASIENTO2 NUMBER;
    V_ID_RESERVA  NUMBER;
    V_CODIGO      VARCHAR2(30);
    V_TOTAL       NUMBER;
    V_ID_PAGO     NUMBER;
    V_COD_PAGO    VARCHAR2(50);
    V_ASIENTOS    T_LISTA_ID;
BEGIN
    SELECT ID_USUARIO INTO V_ID_USUARIO FROM USUARIO WHERE CORREO = 'juan@email.com';

    SELECT ID_FUNCION INTO V_ID_FUNCION FROM (
        SELECT F.ID_FUNCION
        FROM   FUNCION F
        JOIN   PELICULA P ON P.ID_PELICULA = F.ID_PELICULA
        WHERE  P.TITULO = 'Intensamente 2'
        ORDER BY F.FECHA_HORA
    ) WHERE ROWNUM = 1;

    SELECT ID_ASIENTO INTO V_ID_ASIENTO1
    FROM   ASIENTO WHERE FILA = 'A' AND NUMERO = 1
      AND  ID_SALA = (SELECT ID_SALA FROM FUNCION WHERE ID_FUNCION = V_ID_FUNCION);

    SELECT ID_ASIENTO INTO V_ID_ASIENTO2
    FROM   ASIENTO WHERE FILA = 'A' AND NUMERO = 2
      AND  ID_SALA = (SELECT ID_SALA FROM FUNCION WHERE ID_FUNCION = V_ID_FUNCION);

    V_ASIENTOS := T_LISTA_ID(V_ID_ASIENTO1, V_ID_ASIENTO2);

    SP_CREAR_RESERVA(V_ID_USUARIO, V_ID_FUNCION, V_ASIENTOS, V_ID_RESERVA, V_CODIGO, V_TOTAL);
    SP_CONFIRMAR_PAGO(V_ID_RESERVA, 'DEBITO', V_ID_PAGO, V_COD_PAGO);
END;
/

COMMIT;
